### ISSUE TITLE
String color wrong inside procedure calls

### ISSUE THREAD

**Issue by Sti2nd** [alevalv/oz-vscode#4]
You fixed the block commenting coloring (thank you for that), but now I have a problem with the coloring of strings inside procedure/function calls. Unsure if it has always been like this or not.

![string_color](https://user-images.githubusercontent.com/6373430/33526201-cdb524b8-d83d-11e7-9b89-ed188ec22e4c.png)

**Comment by alevalv** [comment]
I think it was always like that, I can reproduce the error locally. will push a fix soon.

Thanks for the report mate

**Comment by Sti2nd** [comment]
No problem, thank you for providing an awesome extension ;)
